version: "3.7"

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - 6969:3306
    volumes:
      - stonks-mysql-data:/var/lib/mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: cs310stonks
      MYSQL_DATABASE: my

volumes:
  stonks-mysql-data: